# Site Settings
title: Xavier Fischer's Blog
tagline: Xavier Fischer's Blog
email: xavier@fischer.ninja
description: >
  All I want to share in the .Net stack, creative coding (OpenFrameworks, Unity) and music (Ableton Live)
baseurl: "/"
url: ""
permalink: pretty

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Xavier Fischer"
      layout: post
      image: https://via.placeholder.com/800x600
      show_sidebar: false

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu
